version: '3'


services:
    client:
        build: client
        ports:
        - "4200:4200"
        container_name: client_container
        restart: always

    api:
        container_name: api
        build: 
            context: api
            
        ports: 
            - "3000:3000"
        links: 
            - mongo
        command: npm run start:dev
    mongo:
        container_name: mongo
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"

            