version: '3'


services:
    client:
        build: client
        ports:
        - "4200:4200"
        container_name: client_container
        restart: always
    
    api:
        build: api
        ports:
            -"8080:3000"
        environment: 
            - DB_UR=mongodb://db_mongo
        volumes: 
            - .:/usr/src/app
            - /usr/src/app/node_modules
    db:
        image: mongo
        container_name: db_mongo
        volumes:
            - mongodata:/data/db
        ports:
            - "27017:27017"
volumes:
    mongodata: 