version: '3'


services:    
    api:
        build: api
        container_name: api
        ports:
            -   "3800:3800"
        restart: always
        links:
            - mongo

    mongo: 
        container_name: mongo
        image: mongo
        ports: 
            - "27017:27017"
        